dev_addr: localhost:9010

site_name: 亚鹿项目手册
site_author: 亚鹿信息
copyright: 版权所有 © [亚鹿信息](https://yaluoo.com)

theme: 
    name: 'material'
    language: 'zh'
    favicon: ' '
    logo:
    icon: ' '
    palette:
        primary: 'black'
        accent: 'deep orange'
        
# 自定义css
extra_css:
- 'assets/css/custom.css'
- 'assets/css/simpleLightbox.min.css'
# 自定义js
extra_javascript:
- 'assets/js/jquery-3.5.0.min.js'
- 'assets/js/simpleLightbox.min.js'
- 'assets/js/custom.js'

plugins:
    - search

# 一些扩展
markdown_extensions:
- markdown.extensions.attr_list
- admonition
- codehilite:
    guess_lang: false
    linenums: false
- toc:
    permalink: true
- footnotes
- meta
- def_list


nav:
    - 项目文档管理工具: contents/docsdev.md
    - Markdown语法: contents/markdown_syntax.md